"""Tests for bundle_detail_md() — behavior/bundle to markdown detail tables."""

from __future__ import annotations

import glob
import re
from pathlib import Path

import pytest

from dot_docs.bundle_to_dot import bundle_detail_md

REPO_ROOT = Path(__file__).parent.parent


# ── Helpers ───────────────────────────────────────────────────────────────────


def _make_yaml(tmp_path: Path, content: str, name: str = "test.yaml") -> Path:
    f = tmp_path / name
    f.write_text(content)
    return f


def _make_md(tmp_path: Path, content: str, name: str = "test.md") -> Path:
    f = tmp_path / name
    f.write_text(content)
    return f


def _make_agent(tmp_path: Path, agent_name: str, description: str) -> None:
    agents_dir = tmp_path / "agents"
    agents_dir.mkdir(exist_ok=True)
    (agents_dir / f"{agent_name}.md").write_text(
        f"---\nmeta:\n  name: {agent_name}\n  description: |\n    {description}\n---\nAgent body.\n"
    )


def _extract_source_hash(md: str) -> str | None:
    match = re.search(r"source_hash:\s*([0-9a-f]+)", md)
    return match.group(1) if match else None


# ── Test: minimal behavior ─────────────────────────────────────────────────────


class TestMinimalBehavior:
    def test_minimal_returns_string(self, tmp_path: Path) -> None:
        """Minimal YAML with no sections → returns a non-empty markdown string."""
        f = _make_yaml(tmp_path, "bundle:\n  name: minimal-test\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert isinstance(result, str)
        assert len(result) > 0

    def test_minimal_has_h1_header(self, tmp_path: Path) -> None:
        """Minimal behavior → H1 header with bundle name."""
        f = _make_yaml(tmp_path, "bundle:\n  name: my-behavior\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "# my-behavior" in result

    def test_minimal_header_contains_composition_detail(self, tmp_path: Path) -> None:
        """H1 header includes 'Composition Detail' suffix."""
        f = _make_yaml(tmp_path, "bundle:\n  name: test-beh\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "Composition Detail" in result

    def test_minimal_has_all_sections(self, tmp_path: Path) -> None:
        """Minimal behavior → all expected section headers present."""
        f = _make_yaml(tmp_path, "bundle:\n  name: all-sections\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "## Tools" in result
        assert "## Context Files" in result
        assert "## Agents" in result
        assert "## Hooks" in result
        assert "## Skills" in result

    def test_minimal_has_per_request_cost_line(self, tmp_path: Path) -> None:
        """Per-request token cost line is present in the output."""
        f = _make_yaml(tmp_path, "bundle:\n  name: cost-test\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "Per-request main-session token cost" in result

    def test_minimal_has_footer_with_source_hash(self, tmp_path: Path) -> None:
        """Footer with source_hash is present."""
        f = _make_yaml(tmp_path, "bundle:\n  name: footer-test\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "source_hash:" in result
        assert "Generated by dot_docs" in result


# ── Test: FileNotFoundError ────────────────────────────────────────────────────


class TestFileNotFound:
    def test_missing_file_raises(self, tmp_path: Path) -> None:
        """FileNotFoundError raised for a path that does not exist."""
        with pytest.raises(FileNotFoundError):
            bundle_detail_md(tmp_path / "nonexistent.yaml")

    def test_missing_md_file_raises(self, tmp_path: Path) -> None:
        """FileNotFoundError raised for a missing .md path."""
        with pytest.raises(FileNotFoundError):
            bundle_detail_md(tmp_path / "missing.md")


# ── Test: per-request token cost ──────────────────────────────────────────────


class TestPerRequestTokenCost:
    def test_zero_cost_behavior_shows_zero(self, tmp_path: Path) -> None:
        """Pure YAML with no context/agents → cost shows ~0 tok."""
        f = _make_yaml(tmp_path, "bundle:\n  name: zero-cost\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "~0 tok" in result

    def test_md_body_adds_to_cost(self, tmp_path: Path) -> None:
        """.md bundle body is counted in per-request token cost."""
        body = "This is a long instruction body. " * 20  # ~165 tokens
        f = _make_md(
            tmp_path,
            f"---\nbundle:\n  name: md-body\n  version: 1.0.0\n---\n{body}",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        # Token cost must be > 0 and contain "tok"
        match = re.search(r"Per-request main-session token cost: ~(\d+) tok", result)
        assert match is not None, f"cost line not found in:\n{result[:500]}"
        cost = int(match.group(1))
        assert cost > 0, "Expected non-zero cost for md bundle with body"

    def test_agent_description_contributes_to_cost(self, tmp_path: Path) -> None:
        """Agent description tokens contribute to per-request cost."""
        description = "A useful agent. " * 20  # non-trivial token count
        _make_agent(tmp_path, "my-agent", description)
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: agent-cost\n  version: 1.0.0\n"
            "agents:\n  include:\n    - foundation:my-agent\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        match = re.search(r"Per-request main-session token cost: ~(\d+) tok", result)
        assert match is not None
        cost = int(match.group(1))
        assert cost > 0


# ── Test: Tools section ────────────────────────────────────────────────────────


class TestToolsSection:
    def test_zero_tools_shows_zero_count(self, tmp_path: Path) -> None:
        """No tools → section shows ## Tools (0)."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-tools\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "## Tools (0)" in result

    def test_zero_tools_shows_no_items_text(self, tmp_path: Path) -> None:
        """No tools → section shows '(No direct tools)' or equivalent empty note."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-tools\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        # Must indicate there are no tools — either via "(No ..." text
        assert "(No" in result

    def test_one_tool_listed(self, tmp_path: Path) -> None:
        """Single tool → tool name appears in tools table."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: one-tool\n  version: 1.0.0\n"
            "tools:\n  - module: tool-delegate\n"
            "    source: git+https://github.com/example/tool@main\n",
        )
        result = bundle_detail_md(f)
        assert "## Tools (1)" in result
        assert "tool-delegate" in result

    def test_multiple_tools_listed(self, tmp_path: Path) -> None:
        """Multiple tools → all tool names appear in table."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: multi-tool\n  version: 1.0.0\n"
            "tools:\n  - module: tool-a\n    source: git+https://github.com/example/a@main\n"
            "  - module: tool-b\n    source: git+https://github.com/example/b@main\n",
        )
        result = bundle_detail_md(f)
        assert "## Tools (2)" in result
        assert "tool-a" in result
        assert "tool-b" in result

    def test_tools_table_has_dash_for_tokens(self, tmp_path: Path) -> None:
        """Tools table shows '—' (em dash) for token cost (schema not accessible from YAML)."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: tool-dash\n  version: 1.0.0\n"
            "tools:\n  - module: tool-x\n    source: git+https://github.com/example/x@main\n",
        )
        result = bundle_detail_md(f)
        # The tools section should contain an em dash indicating unknown cost
        assert "—" in result


# ── Test: Agents section ───────────────────────────────────────────────────────


class TestAgentsSection:
    def test_zero_agents_shows_zero_count(self, tmp_path: Path) -> None:
        """No agents → section shows ## Agents (0)."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-agents\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "## Agents (0)" in result

    def test_zero_agents_shows_no_items_text(self, tmp_path: Path) -> None:
        """No agents → section shows '(No ...' note."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-agents\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "(No" in result

    def test_agent_name_appears_in_table(self, tmp_path: Path) -> None:
        """Agent ref name appears in agents table."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: agent-test\n  version: 1.0.0\n"
            "agents:\n  include:\n    - foundation:my-agent\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "## Agents (1)" in result
        assert "my-agent" in result

    def test_agent_description_tokens_shown(self, tmp_path: Path) -> None:
        """Agent with description file → description tokens shown in table."""
        description = "A detailed agent description. " * 10
        _make_agent(tmp_path, "smart-agent", description)
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: agent-tok\n  version: 1.0.0\n"
            "agents:\n  include:\n    - foundation:smart-agent\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        # Should show ~N tok for the agent
        assert "~" in result
        assert "tok" in result

    def test_missing_agent_file_shows_zero_tokens(self, tmp_path: Path) -> None:
        """Agent ref with no local file → shows ~0 tok."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: ghost-agent\n  version: 1.0.0\n"
            "agents:\n  include:\n    - foundation:ghost-agent\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "ghost-agent" in result
        assert "~0 tok" in result

    def test_agents_table_has_total_row(self, tmp_path: Path) -> None:
        """Agents section with entries has a Total row."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: agents-total\n  version: 1.0.0\n"
            "agents:\n  include:\n    - foundation:some-agent\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "**Total**" in result

    def test_multiple_agents_listed(self, tmp_path: Path) -> None:
        """Multiple agents → all appear in the table."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: multi-agent\n  version: 1.0.0\n"
            "agents:\n  include:\n    - foundation:agent-a\n    - foundation:agent-b\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "## Agents (2)" in result
        assert "agent-a" in result
        assert "agent-b" in result


# ── Test: Context Files section ────────────────────────────────────────────────


class TestContextFilesSection:
    def test_zero_context_shows_zero_count(self, tmp_path: Path) -> None:
        """No context includes → section shows ## Context Files (0)."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-ctx\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "## Context Files (0)" in result

    def test_context_include_filename_appears(self, tmp_path: Path) -> None:
        """context.include file → filename appears in context files table."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: ctx-inc\n  version: 1.0.0\n"
            "context:\n  include:\n    - foundation:context/instructions.md\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "## Context Files (1)" in result
        assert "instructions.md" in result

    def test_context_include_source_column(self, tmp_path: Path) -> None:
        """context.include entries show 'context.include' in Source column."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: ctx-source\n  version: 1.0.0\n"
            "context:\n  include:\n    - foundation:context/instructions.md\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "context.include" in result

    def test_body_mention_source_column(self, tmp_path: Path) -> None:
        """Body @mention entries show '@mention in body' in Source column."""
        f = _make_md(
            tmp_path,
            "---\nbundle:\n  name: mention-src\n  version: 1.0.0\n---\n"
            "@foundation:context/myfile.md\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "@mention in body" in result

    def test_missing_context_file_shows_not_found(self, tmp_path: Path) -> None:
        """Context include that can't be resolved shows '(not found)'."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: missing-ctx\n  version: 1.0.0\n"
            "context:\n  include:\n    - foundation:context/missing.md\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "(not found)" in result

    def test_local_context_file_token_count(self, tmp_path: Path) -> None:
        """Context include that resolves locally → token count shown."""
        # Create a local context file
        ctx_dir = tmp_path / "context"
        ctx_dir.mkdir()
        ctx_content = "Some context content here. " * 50
        (ctx_dir / "myctx.md").write_text(ctx_content)
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: ctx-tok\n  version: 1.0.0\n"
            "context:\n  include:\n    - foundation:context/myctx.md\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        # Should show a non-zero token count for the resolved file
        matches = re.findall(r"~(\d+) tok", result)
        assert any(int(t) > 0 for t in matches), f"Expected non-zero ctx tok:\n{result}"

    def test_context_table_has_source_column_header(self, tmp_path: Path) -> None:
        """Context files table includes a 'Source' column in the header."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: ctx-hdr\n  version: 1.0.0\n"
            "context:\n  include:\n    - foundation:context/any.md\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "Source" in result

    def test_context_table_has_total_row(self, tmp_path: Path) -> None:
        """Context files section with entries has a Total row."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: ctx-total\n  version: 1.0.0\n"
            "context:\n  include:\n    - foundation:context/any.md\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "**Total**" in result

    def test_body_mention_appears_in_context_section(self, tmp_path: Path) -> None:
        """@mention in body → filename appears in Context Files section."""
        f = _make_md(
            tmp_path,
            "---\nbundle:\n  name: mention-ctx\n  version: 1.0.0\n---\n"
            "See @foundation:context/guide.md for details.\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        assert "guide.md" in result

    def test_deduplication_of_context_files(self, tmp_path: Path) -> None:
        """Same file listed twice should only appear once in the table."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: dedup-ctx\n  version: 1.0.0\n"
            "context:\n  include:\n"
            "    - foundation:context/file.md\n"
            "    - foundation:context/file.md\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        # Count occurrences of the filename in the markdown
        assert result.count("file.md") <= 3  # at most header + 1 row + total


# ── Test: Hooks section ────────────────────────────────────────────────────────


class TestHooksSection:
    def test_zero_hooks_shows_zero_count(self, tmp_path: Path) -> None:
        """No hooks → section shows ## Hooks (0)."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-hooks\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "## Hooks (0)" in result

    def test_zero_hooks_shows_no_items_text(self, tmp_path: Path) -> None:
        """No hooks → shows '(No ...' note."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-hooks\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "(No" in result

    def test_hook_module_name_appears(self, tmp_path: Path) -> None:
        """Hook entry → module name appears in hooks table."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: with-hooks\n  version: 1.0.0\n"
            "hooks:\n  - module: hooks-redaction\n"
            "    source: git+https://github.com/example/hooks@main\n",
        )
        result = bundle_detail_md(f)
        assert "## Hooks (1)" in result
        assert "hooks-redaction" in result

    def test_hooks_table_has_no_token_column(self, tmp_path: Path) -> None:
        """Hooks table does NOT have a Tokens column (hooks contribute ~0 tokens)."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: hook-cols\n  version: 1.0.0\n"
            "hooks:\n  - module: hooks-logging\n"
            "    source: git+https://github.com/example/hooks@main\n",
        )
        result = bundle_detail_md(f)
        # Find the hooks section
        hooks_start = result.find("## Hooks")
        hooks_section = result[hooks_start : hooks_start + 300]
        # The Tokens header should NOT appear in the hooks section
        assert "Tokens" not in hooks_section

    def test_multiple_hooks_listed(self, tmp_path: Path) -> None:
        """Multiple hooks → all appear in the table."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: multi-hooks\n  version: 1.0.0\n"
            "hooks:\n  - module: hooks-a\n    source: git+https://github.com/x/a@main\n"
            "  - module: hooks-b\n    source: git+https://github.com/x/b@main\n",
        )
        result = bundle_detail_md(f)
        assert "## Hooks (2)" in result
        assert "hooks-a" in result
        assert "hooks-b" in result


# ── Test: Skills section ───────────────────────────────────────────────────────


class TestSkillsSection:
    def test_no_skills_shows_zero_count(self, tmp_path: Path) -> None:
        """No skills in YAML → section shows ## Skills (0)."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-skills\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "## Skills (0)" in result

    def test_no_skills_shows_no_items_text(self, tmp_path: Path) -> None:
        """No skills → shows '(No direct skills)'."""
        f = _make_yaml(tmp_path, "bundle:\n  name: no-skills\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "No direct skills" in result


# ── Test: source_hash ─────────────────────────────────────────────────────────


class TestSourceHash:
    def test_source_hash_present_in_footer(self, tmp_path: Path) -> None:
        """Footer contains 'source_hash:' label."""
        f = _make_yaml(tmp_path, "bundle:\n  name: hash-test\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        assert "source_hash:" in result

    def test_source_hash_is_hex(self, tmp_path: Path) -> None:
        """source_hash value looks like a SHA-256 hex digest."""
        f = _make_yaml(tmp_path, "bundle:\n  name: hash-hex\n  version: 1.0.0\n")
        result = bundle_detail_md(f)
        h = _extract_source_hash(result)
        assert h is not None, f"source_hash not found in:\n{result[-200:]}"
        assert re.fullmatch(r"[0-9a-f]+", h), f"Not a hex string: {h!r}"
        assert len(h) == 64, f"Expected SHA-256 (64 hex chars), got {len(h)}"

    def test_source_hash_is_deterministic(self, tmp_path: Path) -> None:
        """Same file content → same source_hash on repeated calls."""
        f = _make_yaml(tmp_path, "bundle:\n  name: stable-hash\n  version: 1.0.0\n")
        r1 = bundle_detail_md(f)
        r2 = bundle_detail_md(f)
        h1 = _extract_source_hash(r1)
        h2 = _extract_source_hash(r2)
        assert h1 == h2, "source_hash should be deterministic for the same file"

    def test_source_hash_changes_with_content(self, tmp_path: Path) -> None:
        """Different file content → different source_hash."""
        f1 = _make_yaml(
            tmp_path, "bundle:\n  name: beh-a\n  version: 1.0.0\n", "a.yaml"
        )
        f2 = _make_yaml(
            tmp_path, "bundle:\n  name: beh-b\n  version: 1.0.0\n", "b.yaml"
        )
        h1 = _extract_source_hash(bundle_detail_md(f1))
        h2 = _extract_source_hash(bundle_detail_md(f2))
        assert h1 != h2, "Different file content should produce different source_hash"


# ── Test: .md bundle body instruction tokens ──────────────────────────────────


class TestMdBundleBody:
    def test_md_bundle_body_instruction_tokens(self, tmp_path: Path) -> None:
        """Instructions from .md body are counted in per-request cost."""
        instruction = "Follow these instructions carefully. " * 30
        f = _make_md(
            tmp_path,
            f"---\nbundle:\n  name: instructions\n  version: 1.0.0\n---\n{instruction}",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        match = re.search(r"Per-request main-session token cost: ~(\d+) tok", result)
        assert match is not None
        cost = int(match.group(1))
        expected_min = len(instruction) // 4
        assert cost >= expected_min // 2, (
            f"Expected at least {expected_min // 2} tok from body, got {cost}"
        )

    def test_pure_yaml_has_zero_instruction_cost(self, tmp_path: Path) -> None:
        """Pure YAML behavior (no markdown body) → no instruction tokens in cost."""
        f = _make_yaml(
            tmp_path,
            "bundle:\n  name: pure-yaml\n  version: 1.0.0\n"
            "tools:\n  - module: tool-x\n    source: git+https://github.com/x@main\n",
        )
        result = bundle_detail_md(f, repo_root=tmp_path)
        match = re.search(r"Per-request main-session token cost: ~(\d+) tok", result)
        assert match is not None
        # Tools contribute 0 to token cost (schema cost at runtime)
        assert int(match.group(1)) == 0


# ── Test: real behavior files ─────────────────────────────────────────────────


class TestRealBehaviorAgentsYaml:
    """Tests against the real behaviors/agents.yaml."""

    BEHAVIOR = REPO_ROOT / "behaviors" / "agents.yaml"

    def test_agents_yaml_returns_string(self) -> None:
        """behaviors/agents.yaml → valid markdown string."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert isinstance(result, str)
        assert len(result) > 0

    def test_agents_yaml_has_correct_name(self) -> None:
        """Header contains behavior-agents name."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert "behavior-agents" in result

    def test_agents_yaml_tools_section(self) -> None:
        """agents.yaml has 2 tools → ## Tools (2) present."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert "## Tools (2)" in result
        assert "tool-delegate" in result
        assert "tool-skills" in result

    def test_agents_yaml_context_section(self) -> None:
        """agents.yaml has 2 context includes → ## Context Files (2)."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert "## Context Files (2)" in result
        assert "delegation-instructions.md" in result

    def test_agents_yaml_source_hash_present(self) -> None:
        """agents.yaml output has source_hash in footer."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        h = _extract_source_hash(result)
        assert h is not None
        assert len(h) == 64


class TestRealBehaviorRedactionYaml:
    """Tests against the real behaviors/redaction.yaml."""

    BEHAVIOR = REPO_ROOT / "behaviors" / "redaction.yaml"

    def test_redaction_yaml_returns_string(self) -> None:
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert isinstance(result, str)

    def test_redaction_yaml_has_hook(self) -> None:
        """redaction.yaml has 1 hook → ## Hooks (1) with hooks-redaction."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert "## Hooks (1)" in result
        assert "hooks-redaction" in result

    def test_redaction_yaml_zero_agents(self) -> None:
        """redaction.yaml has no agents → ## Agents (0)."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert "## Agents (0)" in result

    def test_redaction_yaml_zero_tools(self) -> None:
        """redaction.yaml has no tools → ## Tools (0)."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert "## Tools (0)" in result


class TestRealBehaviorSessionsYaml:
    """Tests against the real behaviors/sessions.yaml."""

    BEHAVIOR = REPO_ROOT / "behaviors" / "sessions.yaml"

    def test_sessions_yaml_returns_string(self) -> None:
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert isinstance(result, str)

    def test_sessions_yaml_has_agent(self) -> None:
        """sessions.yaml includes session-analyst agent."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert "session-analyst" in result

    def test_sessions_yaml_has_hook(self) -> None:
        """sessions.yaml includes hooks-session-naming."""
        result = bundle_detail_md(self.BEHAVIOR, repo_root=REPO_ROOT)
        assert "hooks-session-naming" in result


class TestRealRootBundle:
    """Tests against the real bundle.md root bundle."""

    BUNDLE = REPO_ROOT / "bundle.md"

    def test_root_bundle_returns_string(self) -> None:
        result = bundle_detail_md(self.BUNDLE, repo_root=REPO_ROOT)
        assert isinstance(result, str)

    def test_root_bundle_has_foundation_in_header(self) -> None:
        """Root bundle header contains 'foundation'."""
        result = bundle_detail_md(self.BUNDLE, repo_root=REPO_ROOT)
        assert "foundation" in result

    def test_root_bundle_has_tools(self) -> None:
        """Root bundle has direct tools (e.g. tool-filesystem)."""
        result = bundle_detail_md(self.BUNDLE, repo_root=REPO_ROOT)
        assert "tool-filesystem" in result

    def test_root_bundle_has_agents(self) -> None:
        """Root bundle has direct agents (e.g. bug-hunter)."""
        result = bundle_detail_md(self.BUNDLE, repo_root=REPO_ROOT)
        assert "bug-hunter" in result

    def test_root_bundle_has_md_body_tokens(self) -> None:
        """Root bundle has a markdown body → per-request cost > 0."""
        result = bundle_detail_md(self.BUNDLE, repo_root=REPO_ROOT)
        match = re.search(r"Per-request main-session token cost: ~(\d+) tok", result)
        assert match is not None
        assert int(match.group(1)) > 0


# ── Parametrized: all real behavior files ─────────────────────────────────────

_BEHAVIOR_FILES = sorted(
    glob.glob(str(Path(__file__).parent.parent / "behaviors" / "*.yaml"))
)


class TestAllRealBehaviors:
    """Parametrized tests over all real behavior files."""

    @pytest.mark.parametrize(
        "behavior_path",
        _BEHAVIOR_FILES,
        ids=[Path(p).stem for p in _BEHAVIOR_FILES],
    )
    def test_behavior_generates_valid_markdown(self, behavior_path: str) -> None:
        """Every behavior file generates valid markdown with header and footer."""
        repo = Path(__file__).parent.parent
        result = bundle_detail_md(behavior_path, repo_root=repo)
        assert isinstance(result, str)
        assert len(result) > 0
        # Must have H1 header
        assert result.startswith("#"), f"Expected markdown H1 at start:\n{result[:100]}"
        # Must have source_hash in footer
        assert "source_hash:" in result, "Missing source_hash in footer"
        # Must have all section headers
        assert "## Tools" in result
        assert "## Context Files" in result
        assert "## Agents" in result
        assert "## Hooks" in result
        assert "## Skills" in result
